export const ADD_TO_BUFFER = 'ADD_TO_BUFFER'
export const BUTTON_CLICK = 'BUTTON_CLICK'
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS'
export const CLOSE = 'CLOSE'
export const GOOGLE_IMAGE = 'GOOGLE_IMAGE'
export const GOOGLE_IMAGE_ARROW_SELECTOR = '.CIF8af'
export const GOOGLE_IMAGE_INIT_SELECTOR = 'img.rg_i'
export const GOOGLE_IMAGE_MESSAGE =
  'Start of clicking next Google image result'
export const GOOGLE_IMAGE_SUBMIT = 'GOOGLE_IMAGE_SUBMIT'
export const GOOGLE_IMAGE_URL_CONDITION = '&tbm=isch'
export const IMGUR = 'IMGUR'
export const IMGUR_INIT_SELECTOR = '.image-list-link'
export const IMGUR_MESSAGE = 'Repeated click on the next image'
export const IMGUR_SELECTOR = '.navNext'
export const IMGUR_SUBMIT = 'IMGUR_SUBMIT'
export const IMGUR_WARNING_MESSAGE =
  'We have reached the end of this image collection'
export const INIT = 'INIT'
export const MAIN = 'MAIN'
export const RESET = 'RESET'
export const SET_CANCEL = 'SET_CANCEL'
export const SET_TIME_COMPONENT = 'SET_TIME_COMPONENT'
export const SET_TIME_VALUE = 'SET_TIME_VALUE'
export const SET_BUFFER_PROPS = 'SET_BUFFER_PROPS'
export const SLOW_SCROLL = 'SLOW_SCROLL'
export const SLOW_SCROLL_OFF = 'SLOW_SCROLL_OFF'
export const SLOW_SCROLL_MESSAGE = 'SLOW_SCROLL'
export const SLOW_SCROLL_SUBMIT = 'SLOW_SCROLL_SUBMIT'
export const TIME_COMPONENT_VALUE = 'TIME_COMPONENT_VALUE'

export const GOOGLE_SEARCH_URL_CONDITION = 'https://www.google.bg/search'
export const YOUTUBE_URL_CONDITION = 'https://www.youtube.com'

export const GENERIC_CLICK_NEXT = 'GENERIC_CLICK_NEXT'
export const GENERIC_CLICK_NEXT_SUBMIT = 'GENERIC_CLICK_NEXT_SUBMIT'
