export const KEYBINDING = '/home/s/.config/Code/User/keybindings.json'
export const SETTINGS = '/home/s/.config/Code/User/settings.json'
export const JS_SNIPPETS = '/home/s/.config/Code/User/snippets/javascript.json'
export const JSX_SNIPPETS = '/home/s/.config/Code/User/snippets/javascriptreact.json'
export const TS_SNIPPETS = '/home/s/.config/Code/User/snippets/typescript.json'
export const TSX_SNIPPETS = '/home/s/.config/Code/User/snippets/typescriptreact.json'