"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TRUE_FALSE = ['TRUE', 'FALSE'];
exports.ACTIONS_MARKER = '// ACTIONS';
exports.ACTION_INTERFACES_MARKER = '// ACTION_INTERFACES';
exports.COMPONENTS_MARKER = '// COMPONENTS';
exports.CONNECT_EPICS_MARKER = '// CONNECT_EPICS';
exports.CONNECT_STORES_MARKER = '// CONNECT_STORES';
exports.CONSTANTS_MARKER = '// CONSTANTS';
exports.GET_STATE_MARKER = '// GET_STATE';
exports.IMPORT_EPICS_MARKER = '// IMPORT_EPICS';
exports.IMPORT_STORES_MARKER = '// IMPORT_STORES';
exports.IMPORT_CONSTANTS_MARKER = '// IMPORT_CONSTANTS';
exports.INJECT_COMPONENT_MARKER = '// INJECT_COMPONENT';
exports.ROUTES_MARKER = '{/* ROUTES_MARKER */}';
// MODES
exports.ASYNC_MODULE = 'ASYNC_MODULE';
exports.JAVASCRIPT_MODULE = 'JAVASCRIPT_MODULE';
exports.STANDARD_MODULE = 'STANDARD_MODULE';
//# sourceMappingURL=constants.js.map