export const TRUE_FALSE = ['TRUE', 'FALSE']

export const ACTIONS_MARKER = '// ACTIONS'
export const ACTION_INTERFACES_MARKER = '// ACTION_INTERFACES'
export const COMPONENTS_MARKER = '// COMPONENTS'
export const CONNECT_EPICS_MARKER = '// CONNECT_EPICS'
export const CONNECT_STORES_MARKER = '// CONNECT_STORES'
export const CONSTANTS_MARKER = '// CONSTANTS'
export const GET_STATE_MARKER = '// GET_STATE'
export const IMPORT_EPICS_MARKER = '// IMPORT_EPICS'
export const IMPORT_STORES_MARKER = '// IMPORT_STORES'
export const IMPORT_CONSTANTS_MARKER = '// IMPORT_CONSTANTS'
export const INJECT_COMPONENT_MARKER = '// INJECT_COMPONENT'
export const ROUTES_MARKER = '{/* ROUTES_MARKER */}'

// MODES
export const ASYNC_MODULE = 'ASYNC_MODULE'
export const JAVASCRIPT_MODULE = 'JAVASCRIPT_MODULE'
export const STANDARD_MODULE = 'STANDARD_MODULE'
