export const DRAFTS = 'de-en-quotes'
export const ADMIN_PASSWORD = 'ADMIN_PASSWORD'
export const INIT_SYNC = 'INIT_SYNC'
export const LOGOUT = 'LOGOUT'
export const ONCE = 'ONCE'
export const PASSWORD_PROMPT = 'What\'s your password?'
export const SET_PASSWORD = 'SET_PASSWORD'

// ADMIN_INSERT
export const ADMIN_INSERT_NEXT = 'adminInsert@NEXT'
export const ADMIN_INSERT_NEXT_READY = 'adminInsert@NEXT_READY'
export const ADMIN_INSERT_LOAD_KEYS = 'adminInsert@LOAD_KEYS'

export const ADMIN_INSERT_CREATE = 'adminInsert@CREATE'
export const ADMIN_INSERT_DATA_READY = 'adminInsert@DATA_READY'
export const ADMIN_INSERT_LOAD = 'adminInsert@LOAD'
export const ADMIN_INSERT_LOAD_DATA = 'adminInsert@LOAD_DATA'
export const ADMIN_INSERT_READY = 'adminInsert@READY'
export const ADMIN_INSERT_REMOVE = 'adminInsert@REMOVE'
export const ADMIN_INSERT_REMOVE_READY = 'adminInsert@REMOVE_READY'

// RELATED
export const RELATED = 'RELATED'
export const RELATED_CUSTOM_WORD = 'related@CUSTOM_WORD'
export const RELATED_DEFINITION = 'related@DEFINITION'
export const RELATED_INIT = 'adminRepair@RELATED_INIT'
export const RELATED_NAV_NEXT = 'adminRepair@RELATED_NAV_NEXT'
export const RELATED_NAV_PREV = 'adminRepair@RELATED_NAV_PREV'
export const RELATED_READY = 'adminRepair@RELATED_READY'
export const RELATED_REQUEST = 'adminRepair@RELATED_REQUEST'
export const RELATED_SELECT = 'adminRepair@RELATED_SELECT'
export const RELATED_SUGGEST = 'adminRepair@RELATED_SUGGEST'
export const RELATED_TRANSLATE = 'related@TRANSLATE'
export const RELATED_TRANSLATE_READY = 'related@TRANSLATE_READY'
export const SHOW = 'SHOW'
export const SUGGESTIONS = 'SUGGESTIONS'

// ADMIN_REPAIR
export const ADMIN_REPAIR_CHANGE_IMAGE = 'adminRepair@CHANGE_IMAGE'
export const ADMIN_REPAIR_CHANGE_MODE = 'adminRepair@CHANGE_MODE'
export const ADMIN_REPAIR_CHANGE_RANDOM = 'adminRepair@CHANGE_RANDOM'
export const ADMIN_REPAIR_CLICK_IMAGE = 'adminRepair@CLICK_IMAGE'
export const ADMIN_REPAIR_IMAGES_READY = 'adminRepair@IMAGES_READY'
export const ADMIN_REPAIR_INPUT_CHANGE = 'adminRepair@INPUT_CHANGE'
export const ADMIN_REPAIR_LOAD = 'adminRepair@LOAD'
export const ADMIN_REPAIR_LOAD_READY = 'adminRepair@LOAD_READY'
export const ADMIN_REPAIR_NEXT = 'adminRepair@NEXT'
export const ADMIN_REPAIR_NEXT_READY = 'adminRepair@NEXT_READY'
export const ADMIN_REPAIR_READY = 'adminRepair@READY'
export const ADMIN_REPAIR_SEARCH_IMAGE = 'adminRepair@SEARCH_IMAGE'
export const ADMIN_REPAIR_TOGGLE_PC = 'adminRepair@TOGGLE_PC'
export const ADMIN_REPAIR_TO_BULGARIAN = 'adminRepair@TO_BULGARIAN'
export const ADMIN_REPAIR_TO_BULGARIAN_READY = 'adminRepair@TO_BULGARIAN_READY'
export const ADMIN_REPAIR_TRANSLATE = 'adminRepair@TRANSLATE'
export const ADMIN_REPAIR_TRANSLATE_READY = 'adminRepair@TRANSLATE_READY'
export const ADMIN_REPAIR_UPDATE = 'adminRepair@UPDATE'
export const ADMIN_REPAIR_UPDATE_INSTANCE = 'adminRepair@UPDATE_INSTANCE'
export const ADMIN_REPAIR_UPDATE_READY = 'adminRepair@UPDATE_READY'
export const ADMIN_REPAIR_UPDATE_RELATED = 'adminRepair@UPDATE_RELATED'

// SINGLE_INSERT
export const SINGLE_INSERT_CREATE = 'singleInsert@CREATE'
export const SINGLE_INSERT_INPUT_CHANGE = 'singleInsert@INPUT_CHANGE'
export const SINGLE_INSERT_RESET = 'singleInsert@RESET'
export const SINGLE_INSERT_TRANSLATE_PART = 'singleInsert@TRANSLATE_PART'
export const SINGLE_INSERT_TRANSLATE_READY = 'singleInsert@TRANSLATE_READY'
export const SINGLE_INSERT_TRANSLATE_WORD = 'singleInsert@TRANSLATE_WORD'
